### ISSUE TITLE
Extend Travis to python 3.5, 3.6 and 3.7-dev

### ISSUE THREAD

**Issue by ankostis** [kennknowles/python-jsonpath-rw#56]
That would be as simple as adding these lines into `/.travis.yaml`:

```yaml
python:
  - ...
  - 3.5
  - 3.6
  - 3.7-dev

matrix:
  allow_failures:
    - python: 3.7-dev
```
